#define YY_cequal_parser_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 5 "syntax.y"

  #include <stdio.h>

  void yyerror(char* s);
  int yylex();

  extern int yylineno;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_cequal_parser_BISON 1

#ifndef YY_cequal_parser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_cequal_parser_COMPATIBILITY 1
 #else
  #define  YY_cequal_parser_COMPATIBILITY 0
 #endif
#endif

#if YY_cequal_parser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_cequal_parser_LTYPE
   #define YY_cequal_parser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_cequal_parser_STYPE 
   #define YY_cequal_parser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_cequal_parser_DEBUG
   #define  YY_cequal_parser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_cequal_parser_USE_GOTO
  #define YY_cequal_parser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_cequal_parser_USE_GOTO
 #define YY_cequal_parser_USE_GOTO 0
#endif

#ifndef YY_cequal_parser_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_cequal_parser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_cequal_parser_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_cequal_parser_DEBUG */
#endif


#ifndef YY_cequal_parser_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_cequal_parser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_cequal_parser_LSP_NEEDED
#ifndef YY_cequal_parser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_cequal_parser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_cequal_parser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_cequal_parser_STYPE
#define YY_cequal_parser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_cequal_parser_PARSE
#define YY_cequal_parser_PARSE yyparse
#endif
#ifndef YY_cequal_parser_LEX
#define YY_cequal_parser_LEX yylex
#endif
#ifndef YY_cequal_parser_LVAL
#define YY_cequal_parser_LVAL yylval
#endif
#ifndef YY_cequal_parser_LLOC
#define YY_cequal_parser_LLOC yylloc
#endif
#ifndef YY_cequal_parser_CHAR
#define YY_cequal_parser_CHAR yychar
#endif
#ifndef YY_cequal_parser_NERRS
#define YY_cequal_parser_NERRS yynerrs
#endif
#ifndef YY_cequal_parser_DEBUG_FLAG
#define YY_cequal_parser_DEBUG_FLAG yydebug
#endif
#ifndef YY_cequal_parser_ERROR
#define YY_cequal_parser_ERROR yyerror
#endif

#ifndef YY_cequal_parser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_cequal_parser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_cequal_parser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_cequal_parser_PARSE_PARAM
  #define YY_cequal_parser_PARSE_PARAM void
 #endif
#endif

#if YY_cequal_parser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_cequal_parser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_cequal_parser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_cequal_parser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_cequal_parser_PURE
#  ifndef YYPURE
#    define YYPURE YY_cequal_parser_PURE
#  endif
#endif

#ifdef YY_cequal_parser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_cequal_parser_DEBUG 
#  endif
#endif

#ifndef YY_cequal_parser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_cequal_parser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_cequal_parser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_cequal_parser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	T_RES_VAR	258
#define	T_RES_BOOL	259
#define	T_RES_STR	260
#define	T_RES_INT	261
#define	T_RES_IF	262
#define	T_RES_ELSE	263
#define	T_RES_FOR	264
#define	T_RES_WHILE	265
#define	T_RES_SKIP	266
#define	T_RES_STOP	267
#define	T_RES_DEF	268
#define	T_RES_RETURN	269
#define	T_RES_READ	270
#define	T_RES_WRITE	271
#define	T_SYM_OP	272
#define	T_SYM_CP	273
#define	T_SYM_OBK	274
#define	T_SYM_CBK	275
#define	T_SYM_OBC	276
#define	T_SYM_CBC	277
#define	T_SYM_ATR	278
#define	T_SYM_ATP	279
#define	T_SYM_ATM	280
#define	T_SYM_ATMUL	281
#define	T_SYM_ATDIV	282
#define	T_SYM_ATMOD	283
#define	T_SYM_PLS	284
#define	T_SYM_MIN	285
#define	T_SYM_MUL	286
#define	T_SYM_DIV	287
#define	T_SYM_MOD	288
#define	T_SYM_EQL	289
#define	T_SYM_DIF	290
#define	T_SYM_HIG	291
#define	T_SYM_HEQ	292
#define	T_SYM_LES	293
#define	T_SYM_LEQ	294
#define	T_SYM_OR	295
#define	T_SYM_AND	296
#define	T_SYM_NOT	297
#define	T_SYM_SMC	298
#define	T_SYM_CMA	299
#define	T_SYM_INTR	300
#define	T_SYM_COL	301
#define	T_ID	302
#define	T_LIT_INT	303
#define	T_LIT_STR	304
#define	T_LIT_TRUE	305
#define	T_LIT_FALSE	306
#define	LOWER_THEN_ELSE	307
#define	UMINUS	308


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_cequal_parser_CLASS
#define YY_cequal_parser_CLASS cequal_parser
#endif
#ifndef YY_cequal_parser_INHERIT
#define YY_cequal_parser_INHERIT
#endif
#ifndef YY_cequal_parser_MEMBERS
#define YY_cequal_parser_MEMBERS 
#endif
#ifndef YY_cequal_parser_LEX_BODY
#define YY_cequal_parser_LEX_BODY  
#endif
#ifndef YY_cequal_parser_ERROR_BODY
#define YY_cequal_parser_ERROR_BODY  
#endif
#ifndef YY_cequal_parser_CONSTRUCTOR_PARAM
#define YY_cequal_parser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_cequal_parser_CONSTRUCTOR_CODE
#define YY_cequal_parser_CONSTRUCTOR_CODE
#endif
#ifndef YY_cequal_parser_CONSTRUCTOR_INIT
#define YY_cequal_parser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_cequal_parser_USE_CONST_TOKEN
#define YY_cequal_parser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_cequal_parser_USE_CONST_TOKEN != 0
#ifndef YY_cequal_parser_ENUM_TOKEN
#define YY_cequal_parser_ENUM_TOKEN yy_cequal_parser_enum_token
#endif
#endif

class YY_cequal_parser_CLASS YY_cequal_parser_INHERIT
{
public: 
#if YY_cequal_parser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int T_RES_VAR;
static const int T_RES_BOOL;
static const int T_RES_STR;
static const int T_RES_INT;
static const int T_RES_IF;
static const int T_RES_ELSE;
static const int T_RES_FOR;
static const int T_RES_WHILE;
static const int T_RES_SKIP;
static const int T_RES_STOP;
static const int T_RES_DEF;
static const int T_RES_RETURN;
static const int T_RES_READ;
static const int T_RES_WRITE;
static const int T_SYM_OP;
static const int T_SYM_CP;
static const int T_SYM_OBK;
static const int T_SYM_CBK;
static const int T_SYM_OBC;
static const int T_SYM_CBC;
static const int T_SYM_ATR;
static const int T_SYM_ATP;
static const int T_SYM_ATM;
static const int T_SYM_ATMUL;
static const int T_SYM_ATDIV;
static const int T_SYM_ATMOD;
static const int T_SYM_PLS;
static const int T_SYM_MIN;
static const int T_SYM_MUL;
static const int T_SYM_DIV;
static const int T_SYM_MOD;
static const int T_SYM_EQL;
static const int T_SYM_DIF;
static const int T_SYM_HIG;
static const int T_SYM_HEQ;
static const int T_SYM_LES;
static const int T_SYM_LEQ;
static const int T_SYM_OR;
static const int T_SYM_AND;
static const int T_SYM_NOT;
static const int T_SYM_SMC;
static const int T_SYM_CMA;
static const int T_SYM_INTR;
static const int T_SYM_COL;
static const int T_ID;
static const int T_LIT_INT;
static const int T_LIT_STR;
static const int T_LIT_TRUE;
static const int T_LIT_FALSE;
static const int LOWER_THEN_ELSE;
static const int UMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_cequal_parser_ENUM_TOKEN { YY_cequal_parser_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,T_RES_VAR=258
	,T_RES_BOOL=259
	,T_RES_STR=260
	,T_RES_INT=261
	,T_RES_IF=262
	,T_RES_ELSE=263
	,T_RES_FOR=264
	,T_RES_WHILE=265
	,T_RES_SKIP=266
	,T_RES_STOP=267
	,T_RES_DEF=268
	,T_RES_RETURN=269
	,T_RES_READ=270
	,T_RES_WRITE=271
	,T_SYM_OP=272
	,T_SYM_CP=273
	,T_SYM_OBK=274
	,T_SYM_CBK=275
	,T_SYM_OBC=276
	,T_SYM_CBC=277
	,T_SYM_ATR=278
	,T_SYM_ATP=279
	,T_SYM_ATM=280
	,T_SYM_ATMUL=281
	,T_SYM_ATDIV=282
	,T_SYM_ATMOD=283
	,T_SYM_PLS=284
	,T_SYM_MIN=285
	,T_SYM_MUL=286
	,T_SYM_DIV=287
	,T_SYM_MOD=288
	,T_SYM_EQL=289
	,T_SYM_DIF=290
	,T_SYM_HIG=291
	,T_SYM_HEQ=292
	,T_SYM_LES=293
	,T_SYM_LEQ=294
	,T_SYM_OR=295
	,T_SYM_AND=296
	,T_SYM_NOT=297
	,T_SYM_SMC=298
	,T_SYM_CMA=299
	,T_SYM_INTR=300
	,T_SYM_COL=301
	,T_ID=302
	,T_LIT_INT=303
	,T_LIT_STR=304
	,T_LIT_TRUE=305
	,T_LIT_FALSE=306
	,LOWER_THEN_ELSE=307
	,UMINUS=308


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_cequal_parser_PARSE (YY_cequal_parser_PARSE_PARAM);
 virtual void YY_cequal_parser_ERROR(char *msg) YY_cequal_parser_ERROR_BODY;
#ifdef YY_cequal_parser_PURE
#ifdef YY_cequal_parser_LSP_NEEDED
 virtual int  YY_cequal_parser_LEX (YY_cequal_parser_STYPE *YY_cequal_parser_LVAL,YY_cequal_parser_LTYPE *YY_cequal_parser_LLOC) YY_cequal_parser_LEX_BODY;
#else
 virtual int  YY_cequal_parser_LEX (YY_cequal_parser_STYPE *YY_cequal_parser_LVAL) YY_cequal_parser_LEX_BODY;
#endif
#else
 virtual int YY_cequal_parser_LEX() YY_cequal_parser_LEX_BODY;
 YY_cequal_parser_STYPE YY_cequal_parser_LVAL;
#ifdef YY_cequal_parser_LSP_NEEDED
 YY_cequal_parser_LTYPE YY_cequal_parser_LLOC;
#endif
 int   YY_cequal_parser_NERRS;
 int    YY_cequal_parser_CHAR;
#endif
#if YY_cequal_parser_DEBUG != 0
 int YY_cequal_parser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_cequal_parser_CLASS(YY_cequal_parser_CONSTRUCTOR_PARAM);
public:
 YY_cequal_parser_MEMBERS 
};
/* other declare folow */
#if YY_cequal_parser_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_cequal_parser_CLASS::T_RES_VAR=258;
const int YY_cequal_parser_CLASS::T_RES_BOOL=259;
const int YY_cequal_parser_CLASS::T_RES_STR=260;
const int YY_cequal_parser_CLASS::T_RES_INT=261;
const int YY_cequal_parser_CLASS::T_RES_IF=262;
const int YY_cequal_parser_CLASS::T_RES_ELSE=263;
const int YY_cequal_parser_CLASS::T_RES_FOR=264;
const int YY_cequal_parser_CLASS::T_RES_WHILE=265;
const int YY_cequal_parser_CLASS::T_RES_SKIP=266;
const int YY_cequal_parser_CLASS::T_RES_STOP=267;
const int YY_cequal_parser_CLASS::T_RES_DEF=268;
const int YY_cequal_parser_CLASS::T_RES_RETURN=269;
const int YY_cequal_parser_CLASS::T_RES_READ=270;
const int YY_cequal_parser_CLASS::T_RES_WRITE=271;
const int YY_cequal_parser_CLASS::T_SYM_OP=272;
const int YY_cequal_parser_CLASS::T_SYM_CP=273;
const int YY_cequal_parser_CLASS::T_SYM_OBK=274;
const int YY_cequal_parser_CLASS::T_SYM_CBK=275;
const int YY_cequal_parser_CLASS::T_SYM_OBC=276;
const int YY_cequal_parser_CLASS::T_SYM_CBC=277;
const int YY_cequal_parser_CLASS::T_SYM_ATR=278;
const int YY_cequal_parser_CLASS::T_SYM_ATP=279;
const int YY_cequal_parser_CLASS::T_SYM_ATM=280;
const int YY_cequal_parser_CLASS::T_SYM_ATMUL=281;
const int YY_cequal_parser_CLASS::T_SYM_ATDIV=282;
const int YY_cequal_parser_CLASS::T_SYM_ATMOD=283;
const int YY_cequal_parser_CLASS::T_SYM_PLS=284;
const int YY_cequal_parser_CLASS::T_SYM_MIN=285;
const int YY_cequal_parser_CLASS::T_SYM_MUL=286;
const int YY_cequal_parser_CLASS::T_SYM_DIV=287;
const int YY_cequal_parser_CLASS::T_SYM_MOD=288;
const int YY_cequal_parser_CLASS::T_SYM_EQL=289;
const int YY_cequal_parser_CLASS::T_SYM_DIF=290;
const int YY_cequal_parser_CLASS::T_SYM_HIG=291;
const int YY_cequal_parser_CLASS::T_SYM_HEQ=292;
const int YY_cequal_parser_CLASS::T_SYM_LES=293;
const int YY_cequal_parser_CLASS::T_SYM_LEQ=294;
const int YY_cequal_parser_CLASS::T_SYM_OR=295;
const int YY_cequal_parser_CLASS::T_SYM_AND=296;
const int YY_cequal_parser_CLASS::T_SYM_NOT=297;
const int YY_cequal_parser_CLASS::T_SYM_SMC=298;
const int YY_cequal_parser_CLASS::T_SYM_CMA=299;
const int YY_cequal_parser_CLASS::T_SYM_INTR=300;
const int YY_cequal_parser_CLASS::T_SYM_COL=301;
const int YY_cequal_parser_CLASS::T_ID=302;
const int YY_cequal_parser_CLASS::T_LIT_INT=303;
const int YY_cequal_parser_CLASS::T_LIT_STR=304;
const int YY_cequal_parser_CLASS::T_LIT_TRUE=305;
const int YY_cequal_parser_CLASS::T_LIT_FALSE=306;
const int YY_cequal_parser_CLASS::LOWER_THEN_ELSE=307;
const int YY_cequal_parser_CLASS::UMINUS=308;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_cequal_parser_CLASS::token */
#endif
/*apres const  */
YY_cequal_parser_CLASS::YY_cequal_parser_CLASS(YY_cequal_parser_CONSTRUCTOR_PARAM) YY_cequal_parser_CONSTRUCTOR_INIT
{
#if YY_cequal_parser_DEBUG != 0
YY_cequal_parser_DEBUG_FLAG=0;
#endif
YY_cequal_parser_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		183
#define	YYFLAG		-32768
#define	YYNTBASE	54

#define YYTRANSLATE(x) ((unsigned)(x) <= 308 ? yytranslate[x] : 96)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53
};

#if YY_cequal_parser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     7,     9,    11,    17,    19,    23,    25,
    27,    29,    31,    33,    37,    42,    48,    50,    54,    56,
    58,    65,    74,    75,    77,    81,    85,    87,    91,    93,
    97,    99,   101,   103,   105,   107,   109,   111,   113,   117,
   120,   122,   124,   129,   135,   139,   143,   147,   151,   155,
   159,   163,   167,   171,   175,   179,   183,   187,   191,   194,
   196,   198,   200,   205,   206,   208,   212,   213,   216,   218,
   220,   222,   224,   226,   228,   230,   232,   234,   236,   238,
   240,   243,   247,   249,   251,   253,   255,   257,   259,   265,
   273,   279,   289,   292,   295,   298,   302,   308,   312
};

static const short yyrhs[] = {    55,
     0,    56,     0,    55,    56,     0,    57,     0,    65,     0,
     3,    58,    46,    74,    43,     0,    59,     0,    59,    44,
    58,     0,    60,     0,    61,     0,    62,     0,    63,     0,
    72,     0,    60,    23,    78,     0,    72,    19,    48,    20,
     0,    62,    23,    21,    64,    22,     0,    73,     0,    73,
    44,    64,     0,    66,     0,    67,     0,    13,    72,    17,
    68,    18,    75,     0,    13,    72,    17,    68,    18,    46,
    74,    75,     0,     0,    69,     0,    69,    43,    68,     0,
    70,    46,    74,     0,    71,     0,    71,    44,    70,     0,
    72,     0,    72,    19,    20,     0,    47,     0,    48,     0,
    49,     0,    50,     0,    51,     0,     6,     0,     4,     0,
     5,     0,    21,    76,    22,     0,    55,    81,     0,    81,
     0,    72,     0,    72,    19,    78,    20,     0,    78,    45,
    78,    46,    78,     0,    78,    29,    78,     0,    78,    30,
    78,     0,    78,    31,    78,     0,    78,    32,    78,     0,
    78,    33,    78,     0,    78,    34,    78,     0,    78,    35,
    78,     0,    78,    36,    78,     0,    78,    37,    78,     0,
    78,    38,    78,     0,    78,    39,    78,     0,    78,    40,
    78,     0,    78,    41,    78,     0,    17,    78,    18,     0,
    30,    78,     0,    73,     0,    77,     0,    79,     0,    72,
    17,    80,    18,     0,     0,    78,     0,    78,    44,    80,
     0,     0,    81,    82,     0,    83,     0,    75,     0,    84,
     0,    87,     0,    88,     0,    89,     0,    90,     0,    91,
     0,    92,     0,    93,     0,    94,     0,    95,     0,    85,
    43,     0,    77,    86,    78,     0,    23,     0,    24,     0,
    25,     0,    26,     0,    27,     0,    28,     0,     7,    17,
    78,    18,    82,     0,     7,    17,    78,    18,    82,     8,
    82,     0,    10,    17,    78,    18,    82,     0,     9,    17,
    85,    43,    78,    43,    85,    18,    82,     0,    12,    43,
     0,    11,    43,     0,    14,    43,     0,    14,    78,    43,
     0,    72,    17,    80,    18,    43,     0,    15,    77,    43,
     0,    16,    80,    43,     0
};

#endif

#if (YY_cequal_parser_DEBUG != 0) || defined(YY_cequal_parser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    67,    71,    73,    76,    78,    83,    87,    89,    92,    94,
    95,    96,    99,   103,   107,   111,   115,   117,   122,   124,
   127,   131,   135,   137,   138,   141,   145,   147,   150,   152,
   157,   161,   163,   164,   165,   168,   170,   171,   174,   178,
   180,   183,   185,   188,   190,   191,   192,   193,   194,   195,
   196,   197,   198,   199,   200,   201,   202,   203,   204,   205,
   206,   207,   210,   213,   215,   216,   221,   223,   226,   228,
   231,   233,   234,   235,   236,   237,   238,   239,   240,   241,
   244,   248,   252,   254,   255,   256,   257,   258,   261,   263,
   266,   271,   275,   279,   283,   285,   288,   292,   296
};

static const char * const yytname[] = {   "$","error","$illegal.","T_RES_VAR",
"T_RES_BOOL","T_RES_STR","T_RES_INT","T_RES_IF","T_RES_ELSE","T_RES_FOR","T_RES_WHILE",
"T_RES_SKIP","T_RES_STOP","T_RES_DEF","T_RES_RETURN","T_RES_READ","T_RES_WRITE",
"T_SYM_OP","T_SYM_CP","T_SYM_OBK","T_SYM_CBK","T_SYM_OBC","T_SYM_CBC","T_SYM_ATR",
"T_SYM_ATP","T_SYM_ATM","T_SYM_ATMUL","T_SYM_ATDIV","T_SYM_ATMOD","T_SYM_PLS",
"T_SYM_MIN","T_SYM_MUL","T_SYM_DIV","T_SYM_MOD","T_SYM_EQL","T_SYM_DIF","T_SYM_HIG",
"T_SYM_HEQ","T_SYM_LES","T_SYM_LEQ","T_SYM_OR","T_SYM_AND","T_SYM_NOT","T_SYM_SMC",
"T_SYM_CMA","T_SYM_INTR","T_SYM_COL","T_ID","T_LIT_INT","T_LIT_STR","T_LIT_TRUE",
"T_LIT_FALSE","LOWER_THEN_ELSE","UMINUS","program","listDec","dec","decVar",
"listVarSpecs","specVar","specVarSim","specVarSimInit","specVarArr","specVarArrInit",
"arrInit","decSub","decProc","decFunc","paramList","paramDef","paramSpec","param",
"id","literal","type","block","blockdec","varUse","expression","callFunc","expList",
"cmds","cmd","simCmd","cmdAtrib","atrib","atrbSym","cmdIf","cmdWhile","cmdFor",
"cmdStop","cmdSkip","cmdReturn","cmdCallProc","cmdRead","cmdWrite",""
};
#endif

static const short yyr1[] = {     0,
    54,    55,    55,    56,    56,    57,    58,    58,    59,    59,
    59,    59,    60,    61,    62,    63,    64,    64,    65,    65,
    66,    67,    68,    68,    68,    69,    70,    70,    71,    71,
    72,    73,    73,    73,    73,    74,    74,    74,    75,    76,
    76,    77,    77,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    79,    80,    80,    80,    81,    81,    82,    82,
    83,    83,    83,    83,    83,    83,    83,    83,    83,    83,
    84,    85,    86,    86,    86,    86,    86,    86,    87,    87,
    88,    89,    90,    91,    92,    92,    93,    94,    95
};

static const short yyr2[] = {     0,
     1,     1,     2,     1,     1,     5,     1,     3,     1,     1,
     1,     1,     1,     3,     4,     5,     1,     3,     1,     1,
     6,     8,     0,     1,     3,     3,     1,     3,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     3,     2,
     1,     1,     4,     5,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     2,     1,
     1,     1,     4,     0,     1,     3,     0,     2,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     2,     3,     1,     1,     1,     1,     1,     1,     5,     7,
     5,     9,     2,     2,     2,     3,     5,     3,     3
};

static const short yydefact[] = {     0,
     0,     0,     1,     2,     4,     5,    19,    20,    31,     0,
     7,     9,    10,    11,    12,    13,     0,     3,     0,     0,
     0,     0,     0,    23,    37,    38,    36,     0,     8,     0,
     0,    32,    33,    34,    35,    42,    60,    61,    14,    62,
     0,     0,     0,    24,     0,    27,    29,     6,     0,    59,
    64,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    17,    15,     0,
    23,     0,     0,     0,    58,    65,     0,     0,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    57,     0,    16,     0,    67,     0,    21,    25,    26,    28,
    30,    64,    63,    43,     0,    18,    67,     0,    41,     0,
    66,    44,    40,    39,     0,     0,     0,     0,     0,     0,
     0,    64,    42,    70,     0,    68,    69,    71,     0,    72,
    73,    74,    75,    76,    77,    78,    79,    80,    22,     0,
     0,     0,    94,    93,    95,     0,    42,     0,     0,    64,
    83,    84,    85,    86,    87,    88,     0,    81,     0,     0,
     0,    96,    98,    99,     0,    82,     0,     0,     0,     0,
    89,     0,    91,    97,     0,     0,    90,     0,     0,    92,
     0,     0,     0
};

static const short yydefgoto[] = {   181,
     3,     4,     5,    10,    11,    12,    13,    14,    15,    67,
     6,     7,     8,    43,    44,    45,    46,    36,    37,    28,
   124,   108,    38,    76,    40,    77,   109,   126,   127,   128,
   129,   157,   130,   131,   132,   133,   134,   135,   136,   137,
   138
};

static const short yypact[] = {     7,
   -34,   -34,     7,-32768,-32768,-32768,-32768,-32768,-32768,   -28,
   -20,     9,-32768,    29,-32768,    46,    43,-32768,    50,   -34,
    41,    48,    26,   -34,-32768,-32768,-32768,    33,-32768,    41,
    41,-32768,-32768,-32768,-32768,   -10,-32768,-32768,   260,-32768,
    45,    77,    82,    62,    60,    65,    91,-32768,    96,-32768,
    41,    41,    41,    41,    41,    41,    41,    41,    41,    41,
    41,    41,    41,    41,    41,    41,   100,    69,-32768,   -15,
   -34,    50,   -34,   104,-32768,   209,   121,   174,    71,    71,
-32768,-32768,-32768,   301,   301,    49,    49,    49,    49,   277,
   290,   191,-32768,    45,     7,    50,-32768,-32768,-32768,-32768,
-32768,    41,-32768,-32768,    41,-32768,     7,   128,    52,   130,
-32768,   260,    52,-32768,   135,   150,   154,   129,   133,    68,
   -34,    41,    11,-32768,   120,-32768,-32768,-32768,   134,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    41,
   -34,    41,-32768,-32768,-32768,   226,   160,   137,   153,    41,
-32768,-32768,-32768,-32768,-32768,-32768,    41,-32768,   124,   155,
   152,-32768,-32768,-32768,   177,   260,    52,    41,    52,   156,
   165,   243,-32768,-32768,    52,   -34,-32768,   182,    52,-32768,
   201,   202,-32768
};

static const short yypgoto[] = {-32768,
   122,     0,-32768,   196,-32768,-32768,-32768,-32768,-32768,   139,
-32768,-32768,-32768,   147,-32768,   161,-32768,    -1,   -37,   -45,
   -62,-32768,   -92,   -19,-32768,   -97,   144,  -153,-32768,-32768,
  -126,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768
};


#define	YYLAST		340


static const short yytable[] = {    16,
    17,    39,    18,    68,   111,    95,    51,    97,    52,     1,
    49,    50,     9,   171,   160,   173,   125,    19,    16,     2,
   125,   177,    47,    20,   149,   180,    99,   150,   148,    52,
    96,    21,    78,    79,    80,    81,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,   139,   125,   178,
   110,    22,   165,    25,    26,    27,    68,    30,   115,    24,
   116,   117,   118,   119,    23,   120,   121,   122,    41,    47,
    31,    47,    95,    42,   125,    48,   125,    53,    54,    55,
    56,    57,   125,   125,    30,   112,   125,     9,    32,    33,
    34,    35,    32,    33,    34,    35,    69,    31,     9,    70,
   146,    55,    56,    57,    71,    72,    18,   123,    73,    74,
   145,   123,    94,    75,     9,    32,    33,    34,    35,   147,
   159,    93,   161,   101,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65,   166,   103,   147,
    66,   167,   151,   152,   153,   154,   155,   156,   172,   114,
    95,   140,    53,    54,    55,    56,    57,    58,    59,    60,
    61,    62,    63,    64,    65,   123,   141,   123,    66,   169,
   142,   143,   175,   123,   147,   144,   158,   123,    52,   163,
    53,    54,    55,    56,    57,    58,    59,    60,    61,    62,
    63,    64,    65,   104,   170,   164,    66,   168,   174,   179,
   182,   183,    53,    54,    55,    56,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    29,   107,    98,    66,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    64,    65,   106,   100,     0,    66,   105,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
   113,     0,   102,    66,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65,     0,   162,     0,
    66,    53,    54,    55,    56,    57,    58,    59,    60,    61,
    62,    63,    64,    65,     0,   176,     0,    66,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,     0,     0,     0,    66,    53,    54,    55,    56,    57,
    58,    59,    60,    61,    62,    63,     0,    65,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    53,
    54,    55,    56,    57,     0,     0,    60,    61,    62,    63
};

static const short yycheck[] = {     1,
     2,    21,     3,    41,   102,    21,    17,    70,    19,     3,
    30,    31,    47,   167,   141,   169,   109,    46,    20,    13,
   113,   175,    24,    44,   122,   179,    72,    17,   121,    19,
    46,    23,    52,    53,    54,    55,    56,    57,    58,    59,
    60,    61,    62,    63,    64,    65,    66,   110,   141,   176,
    96,    23,   150,     4,     5,     6,    94,    17,     7,    17,
     9,    10,    11,    12,    19,    14,    15,    16,    21,    71,
    30,    73,    21,    48,   167,    43,   169,    29,    30,    31,
    32,    33,   175,   176,    17,   105,   179,    47,    48,    49,
    50,    51,    48,    49,    50,    51,    20,    30,    47,    18,
   120,    31,    32,    33,    43,    46,   107,   109,    44,    19,
    43,   113,    44,    18,    47,    48,    49,    50,    51,   121,
   140,    22,   142,    20,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,   157,    18,   141,
    45,    18,    23,    24,    25,    26,    27,    28,   168,    22,
    21,    17,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,   167,    17,   169,    45,    18,
    17,    43,     8,   175,   176,    43,    43,   179,    19,    43,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    41,    20,    18,    43,    45,    43,    43,    18,
     0,     0,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    20,    95,    71,    45,    29,
    30,    31,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    94,    73,    -1,    45,    46,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    38,    39,    40,    41,
   107,    -1,    44,    45,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    -1,    43,    -1,
    45,    29,    30,    31,    32,    33,    34,    35,    36,    37,
    38,    39,    40,    41,    -1,    43,    -1,    45,    29,    30,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    40,
    41,    -1,    -1,    -1,    45,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    -1,    41,    29,    30,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    29,
    30,    31,    32,    33,    -1,    -1,    36,    37,    38,    39
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_cequal_parser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_cequal_parser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_cequal_parser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_cequal_parser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_cequal_parser_CHAR = (token), YY_cequal_parser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_cequal_parser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_cequal_parser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_cequal_parser_PURE
/* UNPURE */
#define YYLEX           YY_cequal_parser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_cequal_parser_CHAR;                      /*  the lookahead symbol        */
YY_cequal_parser_STYPE      YY_cequal_parser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_cequal_parser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_cequal_parser_LSP_NEEDED
YY_cequal_parser_LTYPE YY_cequal_parser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_cequal_parser_LSP_NEEDED
#define YYLEX           YY_cequal_parser_LEX(&YY_cequal_parser_LVAL, &YY_cequal_parser_LLOC)
#else
#define YYLEX           YY_cequal_parser_LEX(&YY_cequal_parser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_cequal_parser_DEBUG != 0
int YY_cequal_parser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_cequal_parser_CLASS::
#endif
     YY_cequal_parser_PARSE(YY_cequal_parser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_cequal_parser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_cequal_parser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_cequal_parser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_cequal_parser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_cequal_parser_LSP_NEEDED
  YY_cequal_parser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_cequal_parser_LTYPE *yyls = yylsa;
  YY_cequal_parser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_cequal_parser_PURE
  int YY_cequal_parser_CHAR;
  YY_cequal_parser_STYPE YY_cequal_parser_LVAL;
  int YY_cequal_parser_NERRS;
#ifdef YY_cequal_parser_LSP_NEEDED
  YY_cequal_parser_LTYPE YY_cequal_parser_LLOC;
#endif
#endif

  YY_cequal_parser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_cequal_parser_NERRS = 0;
  YY_cequal_parser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_cequal_parser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_cequal_parser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_cequal_parser_LSP_NEEDED
      YY_cequal_parser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_cequal_parser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_cequal_parser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_cequal_parser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_cequal_parser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_cequal_parser_LSP_NEEDED
      yyls = (YY_cequal_parser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_cequal_parser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_cequal_parser_DEBUG != 0
      if (YY_cequal_parser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_cequal_parser_CHAR == YYEMPTY)
    {
#if YY_cequal_parser_DEBUG != 0
      if (YY_cequal_parser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_cequal_parser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_cequal_parser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_cequal_parser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_cequal_parser_DEBUG != 0
      if (YY_cequal_parser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_cequal_parser_CHAR);

#if YY_cequal_parser_DEBUG != 0
      if (YY_cequal_parser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_cequal_parser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_cequal_parser_CHAR, YY_cequal_parser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_cequal_parser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_cequal_parser_CHAR != YYEOF)
    YY_cequal_parser_CHAR = YYEMPTY;

  *++yyvsp = YY_cequal_parser_LVAL;
#ifdef YY_cequal_parser_LSP_NEEDED
  *++yylsp = YY_cequal_parser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_cequal_parser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_cequal_parser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_cequal_parser_LLOC.first_line;
      yylsp->first_column = YY_cequal_parser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_cequal_parser_NERRS;

#ifdef YY_cequal_parser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_cequal_parser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_cequal_parser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_cequal_parser_ERROR_VERBOSE */
	YY_cequal_parser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_cequal_parser_CHAR == YYEOF)
	YYABORT;

#if YY_cequal_parser_DEBUG != 0
      if (YY_cequal_parser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_cequal_parser_CHAR, yytname[yychar1]);
#endif

      YY_cequal_parser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_cequal_parser_LSP_NEEDED
  yylsp--;
#endif

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_cequal_parser_DEBUG != 0
  if (YY_cequal_parser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_cequal_parser_LVAL;
#ifdef YY_cequal_parser_LSP_NEEDED
  *++yylsp = YY_cequal_parser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 300 "syntax.y"


int main(int argc, char** argv){
  yyparse();

  return 0;
}

void yyerror(char* s){
  fprintf(stderr, "Error: %s at line %d\n", s, yylineno);
}
